version: '3'

services: 
  db:
    image: mongo
    restart: always
  api:
    build: server
    restart: always
    depends_on:
      - db
  nginx:
    build: client
    restart: always
    ports: 
      - 8080:80
